# This is the dockerfile for IoT Broker version 5.3.3, September 2016

FROM ubuntu

MAINTAINER 'NEC Laboratories Europe: iotplatform@neclab.eu, Flavio Cirillo: flavio.cirillo@neclab.eu'

#Install postgres
RUN apt-get update
RUN apt-get install postgresql postgis -y
RUN service postgresql start && su -c "psql -d postgres -c \"ALTER USER postgres PASSWORD 'postgres'\"" postgres

#install CouchDB
RUN apt-get install couchdb -y
RUN mkdir /var/run/couchdb
RUN chown -R couchdb:couchdb /var/run/couchdb

#install Maven, Java and GIT
RUN apt-get install maven default-jdk git -y

#Download the NEConfMan SourceCode
WORKDIR /root
RUN git clone https://github.com/Aeronbroker/NEConfMan.git
RUN git clone https://github.com/Aeronbroker/Aeron.git

#Compile and install the ngsi.api bundle
WORKDIR /root/Aeron/IoTbrokerParent
RUN mvn install
WORKDIR /root/Aeron/eu.neclab.iotplatform.ngsi.api
RUN mvn install

#Compile the NEConfMan
WORKDIR /root/NEConfMan/eu.neclab.iotplatform.confman.parent
RUN mvn install
WORKDIR /root/NEConfMan/eu.neclab.iotplatform.confman.builder
RUN mvn install
RUN cp /root/Aeron/eu.neclab.iotplatform.ngsi.api/target/ngsi.api* /root/NEConfMan/eu.neclab.iotplatform.confman.builder/target/builder-*/bundle/

#Setup the NEConfMan
WORKDIR /root/NEConfMan/ConfMan_Runner
RUN chmod +x *.sh
RUN ./setup.sh --auto --propagateauto

#Create the dockerentrypoint
RUN printf "#!/bin/bash\n\n/usr/bin/couchdb > /dev/null &\n\nservice postgresql start && ./exec.sh \$@ --console\n" > confman_dockerentrypoint.sh
RUN chmod +x confman_dockerentrypoint.sh

#Expose the port
EXPOSE 8065

#Start the IoTBroker
ENTRYPOINT ["./confman_dockerentrypoint.sh"]

